apiVersion: v2
description: Hyperledger Fabric Certificate Authority chart (these charts are created by AID:Tech and are currently not directly associated with the Hyperledger project)
name: hlf-ca
version: 1.2.4
appVersion: 1.4.7
keywords:
  - blockchain
  - hyperledger
  - fabric
home: http://hyperledger-fabric-ca.readthedocs.io
sources:
  - https://github.com/hyperledger/fabric-ca
  - https://github.com/k/helm-charts/tree/master/charts/hlf-ca
maintainers:
  - name: alexvicegrab
    email: sasha@aid.technology
  - name: inzamam-iqbal
    email: inzamam@aid.technology
  - name: dbandin
    email: diego@aid.technology
  - name: kbambridge
    email: kbambridge1@gmail.com
icon: https://www.hyperledger.org/wp-content/uploads/2018/04/fabric-logo.png
dependencies:
- name: postgresql
  version: x.x.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
  tags:
    - postgres-database
- name: mysql
  version: x.x.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mysql.enabled
  tags:
    - mysql-database