apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "prysm.fullname" . }}
  labels:
    {{- include "prysm.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "prysm.fullname" . }}
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      {{- include "prysm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "prysm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prysm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: rpc
              containerPort: 4000
              protocol: TCP
            - name: peer-tcp
              containerPort: 13000
              hostPort: 13000
              protocol: TCP
            - name: peer-udp
              containerPort: 12000
              hostPort: 12000
              protocol: UDP
          args:
          - --datadir=/data
          {{- if .Values.httpWeb3Provider }}
          - --http-web3provider={{ .Values.httpWeb3Provider }}
          {{- end}}
          livenessProbe:
            httpGet:
              path: /eth/v1alpha1/node/version
              port: http
          readinessProbe:
            httpGet:
              path: /eth/v1alpha1/node/version
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: data
            mountPath: /data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 128Gi

